config/routes.rb
PhotoCalendar::Application.routes.draw do
  resources :people

  resources :calendars

  root :to => 'calendars#index'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  attr_accessible :name, :single_photo, :full_height_grid
  has_many :people

  def load_people
    separator = "-"
    people.delete_all
    Dir.glob("public/uploads/#{id}/*").each do |filename|
      if [".jpg", ".png"].include? File.extname(filename).downcase
        parts = File.basename(filename, ".*").split separator
        if parts.size >=2
          people.create name: parts[2..-1].join(separator),
            day: Date.new(Date.current.year, parts[0].to_i, parts[1].to_i),
            photo: filename
        end
      end
    end
    people
  end

  def render(year)
    page_size = "A3"
    pdf = Prawn::Document.new page_size: page_size,
      page_layout: :portrait,
      background: "public/uploads/#{id}/background.jpg"
    pdf.font "#{Prawn::DATADIR}/fonts/DejaVuSans.ttf"

    page_width = pdf.bounds.width
    page_height = pdf.bounds.height
    cell_width = pdf.bounds.width / 7
    cell_height = full_height_grid ? 170 : 100
    cell_header_height = 20
    subtitle_box_width = cell_width
    subtitle_box_height = 15

    start_date = Date.new(year)
    end_date = start_date.end_of_year
    (start_date .. end_date).each do |date|
      if date.day == 1
        top_grid_y = (date.all_sundays_in_month.size + 1) * cell_height
        if not full_height_grid
          month_filename = "10" + date.month.to_s.rjust(2,'0') + ".JPG"
          pdf.image "public/uploads/#{id}/#{month_filename}",
            height: page_height - top_grid_y - 80,
            position: :center
        end
        pdf.fill_color "cc0000"
        month_label = I18n.t('date.month_names', locale: :sk)[date.month]
        month_label = "#{month_label.mb_chars.upcase.to_s}    " if full_height_grid
        month_label_y = if full_height_grid then (page_height + top_grid_y + 70)/2 else top_grid_y + 70 end
        pdf.text_box "#{month_label} #{year}",
          at: [0, month_label_y],
          width: 7*cell_width,
          align: full_height_grid ? :center : :left,
          size: 36
        (0..6).each do |weekday|
          if weekday==6
            pdf.fill_color "cc0000"
          else
            pdf.fill_color "000000"
          end
          pdf.text_box I18n.t('date.day_names', locale: :sk)[(weekday + 1) % 7],
            at: [weekday * cell_width, top_grid_y + 20],
            width: cell_width,
            align: :center
          pdf.fill_color "000000"
        end
      end
      x1 = (date.wday - date.previous_monday.wday)%7 * cell_width
      y1 = (date.all_sundays_in_month.select{|i| i>=date.day}.size + 1) * cell_height
      pdf.rectangle [x1, y1], cell_width, cell_height
      pdf.stroke
      pdf.rectangle [x1, y1], cell_width, cell_header_height
      pdf.stroke
      pdf.fill_color "ddddff"
      pdf.fill_rectangle [x1 + 1, y1 - 1], 17, cell_header_height - 2
      if date.sunday? or Holidays.on(Date.civil(year,date.month,date.day),:sk).present?
        pdf.fill_color "cc0000"
      else
        pdf.fill_color "000000"
      end
      pdf.font "Helvetica" do
        pdf.text_box date.day.to_s,
          at: [x1 + 1, y1 - 4],
          height: cell_header_height - 4,
          width: 17,
          align: :center,
          valign: :center,
          size: 12,
          style: :bold
      end
      pdf.text_box PhotoCalendar::Application.config.namesday[date.month][date.day] || "",
        at: [x1 + 15, y1 - 4],
        width: cell_width - 15,
        height: cell_header_height - 4,
        valign: :center,
        align: :center,
        size: 9

      # Find birthdays  

      pdf.fill_color "000000"
      found_people = []
      people.each do |person|
        if person.day.day == date.day and person.day.month == date.month
          found_people << person.name
          if found_people.size == 1
            pdf.image person.photo,
                at: [single_photo ? (x1+x1+cell_width)/2 : x1+1, y1 - cell_header_height-1],
                fit: [cell_width-2, cell_height-cell_header_height-2],
                position: single_photo ? :center : :left
            break if single_photo
          else
            pdf.bounding_box([x1+1, y1 - cell_header_height-1], width: cell_width-1, height: cell_height-cell_header_height-1) do
              pdf.image person.photo,
                position: :right,
                fit: [cell_width, cell_height-cell_header_height-2]
            end
          end
        end
      end
      if found_people.size >= 1
        pdf.transparent(0.5) do
          pdf.fill_rectangle [x1, y1 - cell_height + 15], subtitle_box_width, subtitle_box_height
        end
        
        pdf.fill_color "ffffff"
        pdf.text_box found_people[0] || "",
          at: [x1 + 2, y1 - cell_height + 15],
          width: subtitle_box_width,
          height: subtitle_box_height,
          align: single_photo ? :center : :left,
          valign: :center,
          size: 10
        if found_people.size == 2
          pdf.text_box found_people[1] || "",
            at: [x1 + 2, y1 - cell_height + 15],
            width: subtitle_box_width - 4,
            height: subtitle_box_height,
            align: :right,
            valign: :center,
            size: 10
        end
        pdf.fill_color "000000"
      end
      
      if date.tomorrow.day == 1 and not date.tomorrow.january?
        pdf.start_new_page
      end
    end
    pdf
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :calendar_id, :day, :name, :photo
  belongs_to :calendar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  require 'prawn'
  require 'fastimage'
  
  def index
  	@calendars = Calendar.all
  end

  def show
    calendar = Calendar.find(params[:id])
    if params[:reload]
      calendar.load_people
    end
    pdf = calendar.render (params[:year] || Date.current.year + 1).to_i
    send_data pdf.render, :filename => "x.pdf", :type => "application/pdf", :disposition => 'inline'
  end

  def edit
    calendar = Calendar.find(params[:id])
    if params[:year]
      @year = params[:year].to_i
      @sizes = {}
      @lines = {}
      (1..12).each do |m|
        @lines[m] = Date.new(@year, m).all_sundays_in_month.size + 1
        month_filename = "10" + m.to_s.rjust(2,'0') + ".JPG"
        @sizes[m] = FastImage.size("public/uploads/#{calendar.id}/#{month_filename}")
      end
    end
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/calendars/edit.html.haml
- if @year
  Page width (include margins):
  %input#page_width{value: 841.89, size: 8}
  %br
  Page height:
  %input#page_height{value: 1118.55, size: 8}
  %br
  Cell height:
  %input#cell_height{value: 100, size: 6}
  %br
  %ul
    - (1..12).each do |m|
      %li{id: "month-#{m}"}
        = I18n.t('date.month_names', locale: :sk)[m] + ": "
        %input.width{size: 4, value: @sizes[m][0]}
        x
        %input.height{size: 4, value: @sizes[m][1]}
        %input.lines{type: :hidden, value: @lines[m]}
        %span.result

app/views/calendars/index.html.haml
%ul
  - @calendars.each do |cal|
    %li= link_to cal.name, cal

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoCalendar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :calendar_id %><br />
    <%= f.number_field :calendar_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Day</th>
    <th>Photo</th>
    <th>Calendar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.day %></td>
    <td><%= person.photo %></td>
    <td><%= person.calendar_id %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Day:</b>
  <%= @person.day %>
</p>

<p>
  <b>Photo:</b>
  <%= @person.photo %>
</p>

<p>
  <b>Calendar:</b>
  <%= @person.calendar_id %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>